server:
  port: 0
spring:
  data:
    mongodb:
      url: 'mongodb://localhost:27017'
      database: 'microservices'
      password: ''
  application:
    name: product-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
