spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes[0]:
        id: product-service
        uri:
          lb://product-service
        predicates:
          - Path=/api/product
      routes[1]:
        id: order-service
        uri:
          http://localhost:8761
        predicates:
          - Path=/api/order
      routes[2]:
        id: discovery-server-static
        uri:
          http://eureka:password@${app.eureka-server}:8761
        predicates:
          - Path=/eureka/web
        filters:
          - SetPath=/
      routes[3]:
        id: discovery-server-static
        uri:
          http://eureka:password@${app.eureka-server}:8761
        predicates:
          - Path=/eureka/**
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-boot-microservices-realm
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
logging:
  level:
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka:password@localhost:8761/eureka

server:
  port: 0
